language: ruby
rvm:
  - 2.1.1
  - 2.0.0
  - 1.9.3
env:
  - DB=sqlite
  - DB=mysql
  - DB=postgresql
before_install: cp config/database.travis.yml config/database.yml
script:
  - export RAILS_ENV=test
  - bundle exec rake db:create db:migrate
  - bundle exec rake db:test:prepare
  - bundle exec rake